COVERAGE_DIR := TestResults
REPORT_DIR   := $(COVERAGE_DIR)/CoverageReport

.PHONY: test test-e2e test-e2e-grafana coverage metrics clean

# Unit + integration tests only. E2E tests require live services — use make test-e2e.
test:
	dotnet test --no-restore --filter "Category!=E2E"

# Full LegacyGateway end-to-end suite: clean -> build -> start -> assert -> stop.
test-e2e:
	dotnet test tests/ConduitSharp.LegacyGateway.E2E.Tests --no-restore

# Observability-pipeline E2E: docker compose grafana stack, asserts traces/metrics/logs
# land in Tempo/Prometheus/Loki. Requires a running Docker daemon.
test-e2e-grafana:
	dotnet test tests/ConduitSharp.Grafana.E2E.Tests --no-restore

# mTLS E2E: real client-certificate handshake against an nginx upstream that requires one.
# Cross-platform (Windows/macOS/Linux) — generates certs in .NET and drives docker compose
# via the CLI; only needs Docker. Asserts the gateway with a client cert succeeds and the
# control gateway is rejected.
test-e2e-mtls:
	dotnet test tests/ConduitSharp.Mtls.E2E.Tests --no-restore

# Line/branch coverage over every suite, E2E included. In-process suites are
# collected by coverlet. The E2E suites drive the gateway as a separate OS process
# (make run), so they run under dotnet-coverage, whose profiler follows child
# processes — the spawned gateway contributes real coverage. Cross-process
# profiling needs dynamic instrumentation (Linux/Windows — i.e. CI); on macOS
# arm64 the profiler does not attach and the E2E legs gate on green only.
# Docker-contained gateways (grafana / mTLS stacks) sit outside any profiler on
# every platform; those suites run for correctness, not coverage. Requires a
# running Docker daemon; images are pulled on first run.
coverage:
	rm -rf $(COVERAGE_DIR)
	dotnet test --filter "Category!=E2E" \
		--collect:"XPlat Code Coverage" \
		--results-directory $(COVERAGE_DIR)
	dotnet dotnet-coverage collect -f cobertura -o $(COVERAGE_DIR)/e2e-legacy.cobertura.xml \
		"dotnet test tests/ConduitSharp.LegacyGateway.E2E.Tests --no-restore"
	dotnet dotnet-coverage collect -f cobertura -o $(COVERAGE_DIR)/e2e-embedded.cobertura.xml \
		"dotnet test tests/ConduitSharp.EmbeddedGateway.E2E.Tests --no-restore"
	dotnet dotnet-coverage collect -f cobertura -o $(COVERAGE_DIR)/e2e-embedded-prefixed.cobertura.xml \
		"dotnet test tests/ConduitSharp.EmbeddedGatewayPrefixed.E2E.Tests --no-restore"
	dotnet dotnet-coverage collect -f cobertura -o $(COVERAGE_DIR)/e2e-grafana.cobertura.xml \
		"dotnet test tests/ConduitSharp.Grafana.E2E.Tests --no-restore"
	dotnet dotnet-coverage collect -f cobertura -o $(COVERAGE_DIR)/e2e-mtls.cobertura.xml \
		"dotnet test tests/ConduitSharp.Mtls.E2E.Tests --no-restore"
	dotnet reportgenerator \
		-reports:"$(COVERAGE_DIR)/**/*.cobertura.xml" \
		-targetdir:$(REPORT_DIR) \
		-reporttypes:"Html;TextSummary" \
		-assemblyfilters:"-*.Tests;-GreeterService;-InventoryService;-OrderService" \
		-classfilters:"-AutoGeneratedProgram;-GreeterService.Protos.*"
	@echo ""
	@sed -n '/^Summary/,/^$$/p' $(REPORT_DIR)/Summary.txt
	@echo "Full HTML report: $(REPORT_DIR)/index.html"

# Code metrics (cyclomatic complexity, source lines, maintainability index) over the
# product code — the cross-platform equivalent of Visual Studio's "Calculate Code Metrics".
# Emits metrics.csv + a sortable, color-coded metrics.html.
metrics:
	dotnet run --project tools/CodeMetrics -- src $(COVERAGE_DIR)/metrics
	@echo "HTML report: $(COVERAGE_DIR)/metrics/metrics.html"

clean:
	rm -rf $(COVERAGE_DIR)
