import type { MetricsData } from '../utils/parser';
import { AnimatedNumber } from './AnimatedNumber';

export const Metrics: React.FC<{ metrics: MetricsData; routeName: string }> = ({ metrics, routeName }) => {
  const totalTokens = metrics.totals.in + metrics.totals.out + metrics.totals.cacheRead + metrics.totals.cacheWrite;
  const totalSessions = Object.keys(metrics.sessions).length;
  const avgSessionTokens = totalSessions > 0 ? Math.round(totalTokens / totalSessions) : 0;
  const avgMessageTokens = metrics.totals.messagesSent > 0 ? Math.round(totalTokens / metrics.totals.messagesSent) : 0;
  const wrotePercent = totalTokens > 0 ? Math.round((metrics.totals.out / totalTokens) * 100) : 0;

  let mostUsageInsight = "Reading context";
  const cacheTokens = metrics.totals.cacheRead + metrics.totals.cacheWrite;
  if (cacheTokens > metrics.totals.in && cacheTokens > metrics.totals.out) {
    mostUsageInsight = "Caching";
  } else if (metrics.totals.out > metrics.totals.in && metrics.totals.out > cacheTokens) {
    mostUsageInsight = "Writing output";
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="glass-panel p-6 animate-fade-in flex flex-col items-center text-center" data-testid="metric-totals">
          <h3 className="text-gray-400 text-sm font-medium flex items-center justify-center gap-1">
            Total Usage (Tokens)
            <span className="relative group cursor-help text-xs bg-white/10 rounded-full w-4 h-4 flex items-center justify-center">
              ?
              <span className="absolute bottom-full mb-2 hidden group-hover:block w-48 p-2 bg-gray-800 text-white text-xs rounded shadow-lg z-10 left-1/2 -translate-x-1/2 whitespace-normal">
                Total tokens processed (Input + Output + Cache)
              </span>
            </span>
          </h3>
          <p className="text-3xl font-bold mt-2"><AnimatedNumber value={totalTokens} /></p>
          <p className="text-gray-500 text-xs mt-2"><AnimatedNumber value={metrics.totals.in} /> in + <AnimatedNumber value={metrics.totals.cacheWrite} /> cw + <AnimatedNumber value={metrics.totals.cacheRead} /> cr + <AnimatedNumber value={metrics.totals.out} /> out</p>
        </div>
        <div className="glass-panel p-6 animate-fade-in flex flex-col items-center text-center" style={{ animationDelay: '100ms' }}>
          <h3 className="text-gray-400 text-sm font-medium flex items-center justify-center gap-1">
            Sessions
            <span className="relative group cursor-help text-xs bg-white/10 rounded-full w-4 h-4 flex items-center justify-center">
              ?
              <span className="absolute bottom-full mb-2 hidden group-hover:block w-48 p-2 bg-gray-800 text-white text-xs rounded shadow-lg z-10 left-1/2 -translate-x-1/2 whitespace-normal">
                Count of unique sessions
              </span>
            </span>
          </h3>
          <p className="text-3xl font-bold mt-2"><AnimatedNumber value={totalSessions} /></p>
          <p className="text-gray-500 text-xs mt-2">Each one used <AnimatedNumber value={avgSessionTokens} /> tokens average</p>
        </div>
        <div className="glass-panel p-6 animate-fade-in flex flex-col items-center text-center" style={{ animationDelay: '200ms' }}>
          <h3 className="text-gray-400 text-sm font-medium flex items-center justify-center gap-1">
            Messages Sent
            <span className="relative group cursor-help text-xs bg-white/10 rounded-full w-4 h-4 flex items-center justify-center">
              ?
              <span className="absolute bottom-full mb-2 hidden group-hover:block w-48 p-2 bg-gray-800 text-white text-xs rounded shadow-lg z-10 left-1/2 -translate-x-1/2 whitespace-normal">
                Total API requests made (tokens &gt; 0 or turn &gt; 0)
              </span>
            </span>
          </h3>
          <p className="text-3xl font-bold mt-2"><AnimatedNumber value={metrics.totals.messagesSent} /></p>
          <p className="text-gray-500 text-xs mt-2">Each one cost <AnimatedNumber value={avgMessageTokens} /> tokens average</p>
        </div>
        <div className="glass-panel p-6 animate-fade-in flex flex-col items-center text-center" style={{ animationDelay: '300ms' }}>
          <h3 className="text-gray-400 text-sm font-medium flex items-center justify-center gap-1">
            {routeName === 'All Agents' ? 'All Agents Wrote (Tokens)' : `${routeName.charAt(0).toUpperCase() + routeName.slice(1)} Wrote (Tokens)`}
            <span className="relative group cursor-help text-xs bg-white/10 rounded-full w-4 h-4 flex items-center justify-center">
              ?
              <span className="absolute bottom-full mb-2 hidden group-hover:block w-48 p-2 bg-gray-800 text-white text-xs rounded shadow-lg z-10 left-1/2 -translate-x-1/2 whitespace-normal">
                Total output tokens generated by the model
              </span>
            </span>
          </h3>
          <p className="text-3xl font-bold mt-2"><AnimatedNumber value={metrics.totals.out} /></p>
          <p className="text-gray-500 text-xs mt-2"><AnimatedNumber value={wrotePercent} />% of total -- most usage is {mostUsageInsight}</p>
        </div>
      </div>
      <div className="text-center mt-2">
        <p className="text-gray-500 text-xs flex items-center justify-center gap-1">
          Tokens are how AI measures cost-roughly 0.75 token per word
          <span className="relative group cursor-help bg-white/10 rounded-full w-3 h-3 flex items-center justify-center text-[10px]">
            ?
            <span className="absolute bottom-full mb-2 hidden group-hover:block w-48 p-2 bg-gray-800 text-white text-xs rounded shadow-lg z-10 left-1/2 -translate-x-1/2 whitespace-normal">
              1 token ≈ 0.75 words
            </span>
          </span>
        </p>
      </div>

    </div>
  );
};
